# Generated by Django 4.2.7 on 2023-11-21 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrega2', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='id',
        ),
        migrations.AlterField(
            model_name='empleado',
            name='id_emp',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
