# Generated by Django 4.2.7 on 2023-11-21 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrega2', '0002_remove_empleado_id_alter_empleado_id_emp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_pro', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('ciudad', models.CharField(max_length=40)),
                ('cp', models.CharField(max_length=10)),
                ('telefono', models.CharField(max_length=10, unique=True)),
                ('correo', models.CharField(max_length=30, unique=True)),
                ('habilitado', models.BooleanField(default=True)),
            ],
        ),
    ]
