# Generated by Django 4.2.7 on 2023-11-22 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrega2', '0003_proveedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('codigo', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True, max_length=150, null=True)),
                ('existencia', models.IntegerField(default=0)),
                ('precio_compra', models.DecimalField(decimal_places=2, max_digits=5)),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=5)),
                ('caducidad', models.DateField()),
                ('cura', models.TextField(blank=True, max_length=100, null=True)),
                ('presentacion', models.CharField(choices=[('COMPRIMIDO', 'COMPRIMIDO'), ('CÁPSULA', 'CÁPSULA'), ('TABLETA', 'TABLETA'), ('JARABE', 'JARABE'), ('INYECCIÓN', 'INYECCIÓN'), ('SUPOSITORIOS', 'SUPOSITORIOS'), ('GOTAS', 'GOTAS'), ('AEROSOL', 'AEROSOL'), ('PARCHE', 'PARCHE'), ('INHALADOR', 'INHALADOR'), ('POMADA', 'POMADA'), ('GEL', 'GEL'), ('SOLUCIÓN', 'SOLUCIÓN'), ('BEBIBLES', 'BEBIBLES'), ('SUPLEMENTO', 'SUPLEMENTO')], max_length=20)),
                ('habilitado', models.BooleanField(default=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productosC/')),
            ],
        ),
        migrations.AlterField(
            model_name='empleado',
            name='horario',
            field=models.CharField(choices=[('MATUTINO', 'MATUTINO'), ('VESPERTINO', 'VESPERTINO')], max_length=10),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='puesto',
            field=models.CharField(choices=[('ADMINISTRADOR', 'ADMINISTRADOR'), ('CAJERO', 'CAJERO'), ('MOSTRADOR', 'MOSTRADOR')], max_length=15),
        ),
    ]
