# Generated by Django 4.2.7 on 2023-11-07 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_emp', models.PositiveIntegerField(unique=True)),
                ('nombre', models.CharField(max_length=40, unique=True)),
                ('puesto', models.CharField(max_length=20)),
                ('horario', models.CharField(max_length=20)),
                ('sueldo', models.DecimalField(decimal_places=2, max_digits=5)),
                ('telefono', models.CharField(max_length=10, unique=True)),
                ('correo', models.CharField(max_length=30, unique=True)),
                ('contrasena', models.CharField(max_length=30)),
                ('habilitado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('imagen', models.URLField(blank=True, max_length=255, null=True)),
                ('nombre', models.CharField(max_length=40, unique=True)),
                ('existencia', models.IntegerField(default=0)),
                ('precio_compra', models.DecimalField(decimal_places=2, max_digits=5)),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=5)),
                ('caducidad', models.CharField(max_length=10)),
                ('cura', models.TextField(blank=True, max_length=100, null=True)),
                ('presentacion', models.CharField(max_length=20)),
                ('habilitado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_pro', models.PositiveIntegerField(unique=True)),
                ('nombre', models.CharField(max_length=40, unique=True)),
                ('ciudad', models.CharField(max_length=40)),
                ('cp', models.CharField(max_length=10)),
                ('telefono', models.CharField(max_length=10, unique=True)),
                ('correo', models.CharField(max_length=30, unique=True)),
                ('habilitado', models.BooleanField(default=True)),
            ],
        ),
    ]
