# Generated by Django 4.2.7 on 2023-11-08 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='turno',
            field=models.CharField(default='Matutino', max_length=20),
        ),
    ]
