# Generated by Django 4.2.7 on 2023-11-08 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0002_empleado_turno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='turno',
        ),
        migrations.AlterField(
            model_name='empleado',
            name='sueldo',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
