# Generated by Django 4.2.7 on 2023-11-09 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0004_producto_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=''),
        ),
    ]
