# Generated by Django 4.2.7 on 2023-11-09 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0006_alter_producto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='caducidad',
            field=models.DateField(),
        ),
    ]
